### ISSUE TITLE
Please add a license file & rename the theme to something less generic

### ISSUE THREAD

**Issue by unixorn** [MaxMalinowski/raspberrysh#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but it doesn't have a license file.

Please add a license file - if you don't have one in mind,  I recommend using [choosealicense.com](https://choosealicense.com) to help choose an appropriate one.

Also please rename it to something less generic than `zsh-theme` - even naming it after your github username will make it easy to distinguish from other list entries.

Thanks!

**Comment by MaxMalinowski** [comment]
Hi, thanks for the suggestion. I added a license file and renamed the repo. 
If there's anything else to do please let me know.
